OBJECTS = mysh.o myset.o myenv.o myps.o mycd.o mypwd.o myls.o mycat.o myhead.o mytail.o mysort.o mycp.o mymkdir.o myrm.o

mysh : $(OBJECTS)
	gcc -o mysh $(OBJECTS)

mysh.o : mysh.c
	gcc -c mysh.c

myset.o : myset.c
	gcc -c myset.c

myenv.o : myenv.c
	gcc -c myenv.c

myps.o : myps.c
	gcc -c myps.c

mycd.o : mycd.c
	gcc -c mycd.c

mypwd.o : mypwd.c
	gcc -c mypwd.c

myls.o : myls.c
	gcc -c myls.c

mycat.o : mycat.c
	gcc -c mycat.c

myhead.o : myhead.c
	gcc -c myhead.c

mytail.o : mytail.c
	gcc -c mytail.c

mysort.o : mysort.c
	gcc -c mysort.c

mycp.o : mycp.c
	gcc -c mycp.c

mymkdir.o : mymkdir.c
	gcc -c mymkdir.c

myrm.o : myrm.c
	gcc -c myrm.c
